name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0']
        rubocop: ['0.63.1', '< 1.0']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: configure Gemfile.local
      run: echo "gem 'rubocop', '${{ matrix.rubocop }}'" > Gemfile.local
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rake spec
      run: bundle exec rake spec
